spring:
  security:
    user:
      name: ${ADMIN_NAME:admin}
      password: ${ADMIN_PASSWORD:password}

eureka:
  instance:
    preferIpAddress: true
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URL:http://eureka:password@localhost:8761/eureka/}
