eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    com.netflix: WARN
    org.springframework.web: DEBUG
    com.tictactoecorp: DEBUG

userservice-url: "http://userservice"