server:
  port: ${CONFIG_SERVER_PORT:8888}

spring:
  profiles:
    active: default
  cloud:
    config:
      discovery:
        enabled: true
      server:
        git:
          uri: ${CONFIG_GIT_URL}
          username: ${CONFIG_GIT_USERNAME}
          password: ${CONFIG_GIT_PASSWORD}

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS

---

spring:
  profiles:
    dev
  cloud:
    config:
      discovery:
        enabled: true
      server:
        git:
          uri: ${CONFIG_GIT_URL}
          username: ${CONFIG_GIT_USERNAME}
          password: ${CONFIG_GIT_PASSWORD}
