server:
  port: ${PORT:8888}
spring:
  security:
    user:
      name: ${CONFIG_USERNAME:configUser}
      password: ${CONFIG_PASSWORD:configPassword}
  cloud:
    config:
      discovery:
        enabled: true
      server:
        git:
          uri: ${CONFIG_GIT_URL:https://github.com/lynx-r/tictactoe-config-repo.git}
#          username: ${GITHUB_USERNAME}
#          password: ${GITHUB_PASSWORD}

eureka:
  instance:
    preferIpAddress: true
    # to allow SBA access this service
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URL:http://eureka:password@localhost:8761/eureka}

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS
