eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8761/eureka/}

logging:
  level:
    com.netflix: DEBUG
    org.springframework.http.codec.json: DEBUG
    com.tictactoecorp: DEBUG

userservice-url: "http://userservice"
gameservice-url: "http://gameservice"