discoveryserver:
  image: 'workingbit/com.tictactoe.discovery-server'
  ports:
    - "8761:8761"
  env_file:
    - ${HOME}/Docker/tictactoe-shared.env
configserver:
  image: 'workingbit/com.tictactoe.config-server'
  links:
    - "discoveryserver:discoveryserver"
  ports:
    - "8881:8881"
  env_file:
    - ${HOME}/Docker/tictactoe-shared.env
gatewayserver:
  image: 'workingbit/com.tictactoe.gateway-server'
  links:
    - "discoveryserver:discoveryserver"
    - "configserver:configserver"
  ports:
    - "5555:5555"
  env_file:
    - ${HOME}/Docker/tictactoe-shared.env
adminserver:
  image: 'workingbit/com.tictactoe.admin-server'
  links:
    - "discoveryserver:discoveryserver"
    - "configserver:configserver"
  ports:
    - "9999:9999"
  env_file:
    - ${HOME}/Docker/tictactoe-shared.env
